export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OLD_PASSWORD_INVALID = 'OLD_PASSWORD_INVALID',
  SAME_PASSWORD = 'SAME_PASSWORD',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',

  // Users / Staffs
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  CANNOT_DELETE_ACTIVE_USER = 'CANNOT_DELETE_ACTIVE_USER',
  CANNOT_DEACTIVATE_SELF = 'CANNOT_DEACTIVATE_SELF',
  CANNOT_CHANGE_OWN_ROLE = 'CANNOT_CHANGE_OWN_ROLE',

  // Categories
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_ALREADY_EXISTS = 'CATEGORY_NAME_ALREADY_EXISTS',
  CATEGORY_HAS_ITEMS = 'CATEGORY_HAS_ITEMS',

  // Items / Menu
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  ITEM_OUT_OF_STOCK = 'ITEM_OUT_OF_STOCK',

  // Tables
  TABLE_NOT_FOUND = 'TABLE_NOT_FOUND',
  TABLE_NAME_ALREADY_EXISTS = 'TABLE_NAME_ALREADY_EXISTS',
  TABLE_HAS_ACTIVE_ORDER = 'TABLE_HAS_ACTIVE_ORDER',
  TABLE_CLOSED = 'TABLE_CLOSED',

  // Orders
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  INVALID_ORDER_STATUS_TRANSITION = 'INVALID_ORDER_STATUS_TRANSITION',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // Generic / Infrastructure
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
